### PR TITLE
docs: Made collect_reactions page more explicit.

### PR DESCRIPTION
**Pull request by Jaskowicz1**
collect_reactions never used "override" with virtual void completed(), this changes that. Whilst it's not needed, it's better to be explicit.

This also clears the random indentation on line 36 (prev. line 29).

- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.
- [x] I agree to the terms of the [DCO (Developer Certificate of Origin)]((https://dpp.dev/coding-standards.html))

### CODE REVIEW

**Comment by Jaskowicz1** [comment]
PR is marked as draft until #779 is complete so I can deal with the conflicts.

**Comment by Jaskowicz1** [comment]
It appears "Files Changes" now shows changes from #779.

**Comment by braindigitalis** [comment]
needs to be merged to dev not master, I have updated this

**Review by braindigitalis — APPROVED** [review]

**Comment by Jaskowicz1** [comment]
> needs to be merged to dev not master, I have updated this

Thought I had, sorry about that!!

**Review by Commandserver — APPROVED** [review]

**Pull request merged**
