### PR TITLE
ci: allow runners to use mold, increased concurrency to 4

### PR DESCRIPTION
**Pull request by Jaskowicz1**
This PR attempts to speed up the action runners by allowing them to use mold and also changing the concurrency to 3 instead of 2 (github action runners were updated to 4 cores a while ago).

The checklist does not apply here.

### CODE REVIEW

**Comment by braindigitalis** [comment]
can we bump up the concurrency on gh runners to 4 then instead of 3? do we see any improvement?

**Comment by Jaskowicz1** [comment]
> can we bump up the concurrency on gh runners to 4 then instead of 3? do we see any improvement?

That was done in the recent push :)

Seems that we barely get an improvement across the board. A couple of runners are faster and a couple of them aren't any different.

**Comment by Mishura4** [comment]
I mean mold will only affect linking which is a fraction of the time the runners spend on D++
mold really shines when LTO is enabled

**Comment by Jaskowicz1** [comment]
@braindigitalis Ignore last comment about "little results".

CodeQL is now ~3 minutes faster (comparing https://github.com/brainboxdotcc/DPP/actions/runs/9921615282/job/27409774387?pr=1197 with https://github.com/brainboxdotcc/DPP/actions/runs/9921876515/job/27410330135?pr=1198).

The Action Runners now builds on average 30 seconds to 2 minutes faster (seems like Clang15, g++13, g++14, and g++15, were nearly 2 minutes faster now).

Self hosted runner arm7hf didn't benefit at all, same with self hosted runner arm64.

OSX didn't have any change to concurrency, nor linker. Neither did Windows.

**Comment by Jaskowicz1** [comment]
> I mean mold will only affect linking which is a fraction of the time the runners spend on D++ mold really shines when LTO is enabled

true true, the reason it's dropped a good bit is the concurrency being upped to 4.

**Comment by Jaskowicz1** [comment]
CodeQL is now down another minute! We're seeing 17 mins now!

**Review by braindigitalis — APPROVED** [review]

**Pull request merged**
