### PR TITLE
docs: add auto testing of examples

### PR DESCRIPTION
**Pull request by braindigitalis**
This PR splits out the examples into `docpages/example_code`. These are individual .cpp files which should be able to be compiled as standalone programs into an executable.

There is also a CMakeLists.txt that builds them, and an action that runs this test build on push. This way we can identify bad examples that dont even compile. It also allows us to properly use syntax highlighting and linting on them and ensure they meet our code style guide.

- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.

### CODE REVIEW

**Comment by braindigitalis** [comment]
An example of a successful run of the action:
https://github.com/brainboxdotcc/DPP/actions/runs/6179898895/job/16775550064?pr=854

**Comment by Jaskowicz1** [comment]
Not reviewed it yet, but this is an extremely good feature to go through with for the docs.

My biggest question is, will the GitHub actions test this on different compilers (for example, Clang, G++, and MSVC)? If not, we should look into this as we've had an issue in the past with this.

**Comment by braindigitalis** [comment]
> Not reviewed it yet, but this is an extremely good feature to go through with for the docs.
> 
> My biggest question is, will the GitHub actions test this on different compilers (for example, Clang, G++, and MSVC)? If not, we should look into this as we've had an issue in the past with this.

no I think that is overkill. we would have to build 3 copies of dpp with coro, and compile about 40 example programs on each. these are impossible to test without spamming pushes to GitHub and waiting for hours each time, as there is no way to locally simulate a windows GitHub action. smells like arm6 cross compile all over again

**Comment by Jaskowicz1** [comment]
> > Not reviewed it yet, but this is an extremely good feature to go through with for the docs.
> > My biggest question is, will the GitHub actions test this on different compilers (for example, Clang, G++, and MSVC)? If not, we should look into this as we've had an issue in the past with this.
> 
> no I think that is overkill. we would have to build 3 copies of dpp with coro, and compile about 40 example programs on each. these are impossible to test without spamming pushes to GitHub and waiting for hours each time, as there is no way to locally simulate a windows GitHub action. smells like arm6 cross compile all over again

That's understandable. Still great either way!

**Review by RealTimeChris — APPROVED** [review]

**Pull request merged**
