### PR TITLE
perf: remove copying of audio buffer before encrypting

### PR DESCRIPTION
**Pull request by Fluiser**
Removing meaningless allocation and copying memory.

Communication with the system is expensive.

### CODE REVIEW

**Comment by braindigitalis** [comment]
is this fully tested, with both send and receive of data, and mixing audio?

the data copies are not meaningless at all and are required to prevent buffers overwriting themselves inside opus and sodium - please ensure everything works correctly. 

I do not think this is safe.

**Review by braindigitalis — CHANGES_REQUESTED** [review]
please ensure unit tests pass and that a sample program is written to show this. you removed the pull request template text so I have no way of knowing if this was done.

**Comment by Mishura4** [comment]
According to the [sodium docs](https://libsodium.gitbook.io/doc/secret-key_cryptography/secretbox), the buffers can overlap. However yes it would be good to confirm everything still works.

**Comment by Mishura4** [comment]
I've also renamed the PR to comply with the [coding style standards](https://dpp.dev/coding-standards.html).

**Comment by Fluiser** [comment]
std::vector lives in scope, as does its argument. If we assume that the memory is not available by the label, then it may also be inaccessible at the time of copying to the vector.

**Pull request closed without merging**
