### PR TITLE
docs: remade the linux.md page.

### PR DESCRIPTION
**Pull request by Jaskowicz1**
This PR remakes the `linux.md` page, basically taking the old buildcmake.md page and adding it here (but, ofc, improved), meaning the page now covers g++ and CMake. This PR also merges the changes on `linux.md` from #820.

## Documentation change checklist

- [x] My documentation changes follow the same style as the rest of the documentation and any examples follow the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR (via running `oxygen`, and testing examples).
- [x] I have not moved any existing pages or changed any existing URLs without strong justification as to why.
- [x] I have not generated content using AI or a desktop utility such as grammarly.

### CODE REVIEW

**Review by braindigitalis — CHANGES_REQUESTED** [review]
not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain.
simply link to the cmake guide at the bottom as we did before?

**Comment by Jaskowicz1** [comment]
> not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain. simply link to the cmake guide at the bottom as we did before?

They're not the same. The CMake guide no longer uses source, the new addition here shows CMake with source. Ideally, I'd like two separate pages, unless you can come up with a better idea!

**Comment by braindigitalis** [comment]
> > not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain. simply link to the cmake guide at the bottom as we did before?
> 
> They're not the same. The CMake guide no longer uses source, the new addition here shows CMake with source. Ideally, I'd like two separate pages, unless you can come up with a better idea!

problem is this a guide on how to build the lib and now it's also a guide on how to build a bot... the lines are blurred and it isn't so clear any more. perhaps a separate new page for it that this one links to?

**Comment by Jaskowicz1** [comment]
> > > not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain. simply link to the cmake guide at the bottom as we did before?
> > 
> > 
> > They're not the same. The CMake guide no longer uses source, the new addition here shows CMake with source. Ideally, I'd like two separate pages, unless you can come up with a better idea!
> 
> problem is this a guide on how to build the lib and now it's also a guide on how to build a bot... the lines are blurred and it isn't so clear any more. perhaps a separate new page for it that this one links to?

Yeah that's actually a good point, I didn't really think of that. So, if we're to make a separate page for building a bot using source with CMake, where would we place that? I don't think placing it next to the `buildcmake.md` page is a good idea.

**Comment by braindigitalis** [comment]
> > > > not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain. simply link to the cmake guide at the bottom as we did before?
> > > 
> > > 
> > > They're not the same. The CMake guide no longer uses source, the new addition here shows CMake with source. Ideally, I'd like two separate pages, unless you can come up with a better idea!
> > 
> > 
> > problem is this a guide on how to build the lib and now it's also a guide on how to build a bot... the lines are blurred and it isn't so clear any more. perhaps a separate new page for it that this one links to?
> 
> Yeah that's actually a good point, I didn't really think of that. So, if we're to make a separate page for building a bot using source with CMake, where would we place that? I don't think placing it next to the `buildcmake.md` page is a good idea.

bury it at the bottom of this one with a hyperlink to it so that you have to be looking for it to find it, this encourages people by default to install how we can support them easier, same way we funnel them towards the windows template.

**Comment by Jaskowicz1** [comment]
> > > > > not sure we should be merging the pages together... it means duplicated content on Google which is bad and means two places to maintain. simply link to the cmake guide at the bottom as we did before?
> > > > 
> > > > 
> > > > They're not the same. The CMake guide no longer uses source, the new addition here shows CMake with source. Ideally, I'd like two separate pages, unless you can come up with a better idea!
> > > 
> > > 
> > > problem is this a guide on how to build the lib and now it's also a guide on how to build a bot... the lines are blurred and it isn't so clear any more. perhaps a separate new page for it that this one links to?
> > 
> > 
> > Yeah that's actually a good point, I didn't really think of that. So, if we're to make a separate page for building a bot using source with CMake, where would we place that? I don't think placing it next to the `buildcmake.md` page is a good idea.
> 
> bury it at the bottom of this one with a hyperlink to it so that you have to be looking for it to find it, this encourages people by default to install how we can support them easier, same way we funnel them towards the windows template.

I like that idea haha. However, if it's not listed as a "subpage" anywhere, it'll become a top page (like FAQ) so it needs to be under some sub-section. I think we should also have a discussion about the linux template, if you're available for that :)

**Pull request closed without merging**
