### PR TITLE
User-installed commands

### PR DESCRIPTION
**Pull request by raxyte**
Adds required support for user-installed commands.

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [ ] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Comment by ruslan-ilesik** [comment]
I believe you should cover this feature with unit tests. (Look how other "online" tests are made for similar things)

**Comment by Mishura4** [comment]
Try using DPP_DEPRECATED instead of [[deprecated]] to fix those errors on windows

**Comment by raxyte** [comment]
Don't have time to get back to it. Can close if no one else can take over it.

**Comment by Jaskowicz1** [comment]
I can try take over :)

**Comment by braindigitalis** [comment]
if theres no movement on this, i'm happy to take it on?

**Comment by Jaskowicz1** [comment]
Please do, whilst I want to do it, I do not have the time :)

**Review by braindigitalis — APPROVED** [review]

**Comment by braindigitalis** [comment]
i have merged this into a branch on the dpp main repo called `userapps` and will continue to work on it. This has been done without rebase, so that credit for existing work is preserved.

**Pull request merged**
