### PR TITLE
Fixing issue #604

### PR DESCRIPTION
**Pull request by flankytingz**
Removed if statements to always update guild member's roles and nick when converting to JSON.

### CODE REVIEW

**Comment by braindigitalis** [comment]
you now can't edit a user without setting a nickname if you do this?

similarly, you must always specificy the roles or it's going try to clear them...

not sure this fix will solve the problem without introducing more problems...?

**Comment by flankytingz** [comment]
> you now can't edit a user without setting a nickname if you do this?
> 
> similarly, you must always specificy the roles or it's going try to clear them...
> 
> not sure this fix will solve the problem without introducing more problems...?

All parameters to this endpoint are optional and nullable. When moving members to channels, the API user must have permissions to both connect to the channel and have the MOVE_MEMBERS permission. 
https://discord.com/developers/docs/resources/guild#modify-guild-member

I would think that means if set to null, the roles and nickname will be removed.

**Comment by braindigitalis** [comment]
yes, but you have no way to set them to null right now?

**Comment by flankytingz** [comment]
> yes, but you have no way to set them to null right now?

Just realized that. They should be set to null, not "".

**Comment by flankytingz** [comment]
This is assign nick and roles as null if they are empty.

```c++
if (this->nickname.empty()) {
    j["nick"] = nullptr;
} else {
    j["nick"] = this->nickname;
}

if (this->roles.empty()) {
    j["roles"] = nullptr;
} else {
    j["roles"] = {};
    for (auto & role : roles)
        j["roles"].push_back(std::to_string(role));
}
```

**Comment by Axyte** [comment]
This stuff isn't going to work, user needs to decide whether the fields are to be cleared or they simply aren't present. This requires breaking API with either Booleans or introducing `std::optional`.

**Comment by Commandserver** [comment]
Also, you should use `json::value_t::null`

**Comment by Commandserver** [comment]
> This stuff isn't going to work, user needs to decide whether the fields are to be cleared or they simply aren't present. This requires breaking API with either Booleans or introducing `std::optional`.

Already tried the std::optional thing in #605
... looked too ugly. Maybe the booleans are a better idea

**Comment by Axyte** [comment]
Uh, that isn't how I'd typically imagine `std::optional` here.

It would be the member of class so
```cpp
class guild_member {
    std::optional<std::string> nickname;
    /* ..... */
};
```
Although it would be much better, it's simply a breaking change in the API.

**Pull request closed without merging**
