### PR TITLE
added color constants

### PR DESCRIPTION
**Pull request by DJOetzi**
as the title says I added color constants for quite some colors

### CODE REVIEW

**Comment by es183923** [comment]
Where did you get the colors from?

**Comment by DJOetzi** [comment]
I collected them from various sources (namely Paletton and Discord4J's colors). I was particularly looking for some neat shades I knew and some which I thought look nice.
Should I list the sources?

**Comment by braindigitalis** [comment]
you need to fix the spelling fail by adding the odd colour name to the .cspell.json file, or give it a less weird name

**Comment by braindigitalis** [comment]
for reference the odd colour name is "hoki", no clue what that's supposed to mean... I suggest a more readable name in its place.

**Comment by DJOetzi** [comment]
done

**Comment by es183923** [comment]
Many of these are not actual discord colors. For example, green is marked as `0x00FF00`, while dicscord website clearly states that it is supposed to be `0x57F287`.

**Comment by Axyte** [comment]
> Many of these are not actual discord colors. For example, green is marked as `0x00FF00`, while dicscord website clearly states that it is supposed to be `0x57F287`.

....what?

**Comment by es183923** [comment]
> > Many of these are not actual discord colors. For example, green is marked as `0x00FF00`, while dicscord website clearly states that it is supposed to be `0x57F287`.
> 
> ....what?

https://discord.com/branding

**Comment by Axyte** [comment]
So what? Green *is* `0x00FF00`. You're confusing what discord has branded as their color scheme with the RGB value of pure green.

**Comment by es183923** [comment]
> So what? Green _is_ `0x00FF00`. You're confusing what discord has branded as their color scheme with the RGB value of pure green.

I thought that as D++ is a *Discord* API Library, it should be using the colors provided by Discord, not the RGB colors.

**Comment by es183923** [comment]
Some of the colors currently provided in D++ are in fact actual Discord colors as well. For example, `light_sea_green` is `0x1ABC9C`, which is indeed one of the default colors for roles.

**Comment by es183923** [comment]
@braindigitalis, Could you give your opinion on this?

**Comment by braindigitalis** [comment]
these are for embeds so it doesn't really matter

**Comment by es183923** [comment]
Ok, I'll leave it the way it is, and use my own colors instead.

**Pull request merged**
