### PR TITLE
Adding clang-format, clang

### PR DESCRIPTION
**Pull request by AA1999**
I couln't add the other two files in this PR, I'll make another one ig

This file automates the clang-format run on new PRs afaik

### CODE REVIEW

**Comment by braindigitalis** [comment]
seems gh doesn't want to pick up the job? it's sat waiting 1h 30m...

**Comment by braindigitalis** [comment]
> Analysis should be only performed on library code.
> 
> ```yaml
> name: clang-format
> on: [push, pull_request]
> jobs:
>   formatting-check:
>     name: Format check
>     runs-on: ubuntu-latest
>     strategy:
>           matrix:
>             path:
>               - 'src'
>               - 'include'
>     steps:
>     - uses: actions/checkout@v2
>     - name: Run clang-format style check for C/C++ programs.
>       uses: jidicula/clang-format-action@v4.2.0
>       with:
>         clang-format-version: '13'
>         check-path: ${{ matrix.path }}
> ```
> 
> from [clang-format-action's readme](https://github.com/jidicula/clang-format-action)

this still includes fmt and nlohmann json which are subdirs of include/dpp, you'd need to exclude them

**Comment by rgnter** [comment]
```yaml
name: clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    strategy:
          matrix:
            path:
              - 'src'
              - 'include'
               exclude: '(fmt|nlohmann) ' 
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
```

**Comment by rgnter** [comment]
is exclude supposed to be an array entry?

**Comment by braindigitalis** [comment]
this is now part of a branch called clang-format-tidy, where work will continue on getting this in a usable state for the project.
Thanks for getting the ball rolling!

**Pull request closed without merging**
