### PR TITLE
Add autocomplete support for subcommands arguments

### PR DESCRIPTION
**Pull request by Neko-Life**
Tested and works for me.

### CODE REVIEW

**Comment by braindigitalis** [comment]
why is the submodule changed for doxygen-awesome-css?

**Comment by braindigitalis** [comment]
your branch is 110 commits behind, please update it, that's ancient!

**Comment by Neko-Life** [comment]
Oh actually I'm not sure, thought it was an update from the submodule,
guess I'm gonna revert that

**Comment by Neko-Life** [comment]
Actually that's only the master branch, I'm making PR from the dev branch

**Pull request merged**
