### PR TITLE
breaking: delete message count on `cluster::guild_ban_add` is now scaled in seconds instead of days

### PR DESCRIPTION
**Pull request by Commandserver**
https://github.com/discord/discord-api-docs/commit/7e3e3a3de46a909c9a5bc04404f0df9a806e7271

### CODE REVIEW

**Comment by Commandserver** [comment]
hm should we add something in the method to log a warning message when a value of 0 to 7 is passed to `delete_message_seconds`? So that the users know they should take a look at it

**Comment by braindigitalis** [comment]
> hm should we add something in the method to log a warning message when a value of 1 to 7 is passed to `delete_message_seconds`? So that the users know they should take a look at it

yes sounds.sensible

**Comment by Commandserver** [comment]
We can also multiply the value, if its 1 - 7, by 86400 seconds. So basically it will calculate the value to seconds. I mean who tf will ban a player and delete the messages of lets say the last 5 seconds. Think we can asume then, that they've not updated their code.

**Comment by Commandserver** [comment]
Or both, logging and multiplying

**Comment by braindigitalis** [comment]
definitely just the warning - changing the value is confusing and what if you actually want a 5 second delete range?

**Comment by Commandserver** [comment]
can you do the logging stuff for me @braindigitalis ?

**Comment by Commandserver** [comment]
i dont really know how to do that

**Comment by braindigitalis** [comment]
```cpp
this->log(ll_warn, "Oopsy woopsy you did a fucky wucky!");
```
this, inside any cluster method. not that literal text though lol

**Pull request merged**
