### PR TITLE
Add namespace comment

### PR DESCRIPTION
**Pull request by fffelix-huang**
No functional change.

### CODE REVIEW

**Comment by braindigitalis** [comment]
are there no other namespaces missing a similar comment? would be more likely to approve the PR if there was more substance to it. Please check for other missing namespace closing comments and add them into this PR :)

**Comment by fffelix-huang** [comment]
There are several other missing namespace closing comment (Example: `include/dpp/unicode_emoji.h`). However since they are auto-generated I didn't add them.

**Comment by braindigitalis** [comment]
> There are several other missing namespace closing comment (Example: `include/dpp/unicode_emoji.h`). However since they are auto-generated I didn't add them.

perhaps you can track down where the generators do this, and fix the generators? :)

**Comment by Jaskowicz1** [comment]
why are we letting this PR be a thing btw, we discussed last year we did not care about this.

**Comment by braindigitalis** [comment]
You are right, we did agree that, so it isnt needed.
On the opposite side of the coin there are a ton of these in src/dpp/dave that could likely be removed.

**Pull request closed without merging**
