### PR TITLE
fix, chore, perf, style, feat, improv, refactor, test, docs: update dispatcher.h/.cpp

### PR DESCRIPTION
**Pull request by Mishura4**
This PR allows events to be move and copy assigned.

That's it. Definitely nothing else in 800 line changes.

Just kidding :
 - Fixes style issues in dispatcher.h and dispatcher.cpp
 - Adds unit tests checking that the types can be copy constructed and assigned as well as move constructed and assigned
 - Changes the thread_local `stop_event` for event cancellation into a mutable bool inside of event_dispatch_t (yes, it still works)
 - Adds various small optimizations in dispatcher.cpp
 - Fixes some weird things (e.g. `message_create_t::send` taking with a non-const lvalue reference to dpp::message
 - Makes VS2022 use PCH because why not

API remains the same for everything

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Review by braindigitalis — APPROVED** [review]
squeaky clean new code, when can we merge it 😄

**Comment by Jaskowicz1** [comment]
> squeaky clean new code, when can we merge it 😄

now plz, with a release too if possible <3

**Comment by Mishura4** [comment]
When I fix ARM 😭
And tests apparently?

**Comment by braindigitalis** [comment]
your new unit test fails

**Pull request merged**
