### PR TITLE
docs: added OpenBSD to readme

### PR DESCRIPTION
**Pull request by mrtuxa**
related to this PR #880

### CODE REVIEW

**Comment by braindigitalis** [comment]
@mrtuxa are the many issues with openbsd that @Jaskowicz1 is having an "us problem", or is there a fix? Do they need to be part of this change if we are claiming its fully supported?

**Comment by mrtuxa** [comment]
> @mrtuxa are the many issues with openbsd that @Jaskowicz1 is having an "us problem", or is there a fix? Do they need to be part of this change if we are claiming its fully supported?

i will do some tests the next days

**Comment by Jaskowicz1** [comment]
> > @mrtuxa are the many issues with openbsd that @Jaskowicz1 is having an "us problem", or is there a fix? Do they need to be part of this change if we are claiming its fully supported?
> 
> i will do some tests the next days

Thank you :)

**Comment by mrtuxa** [comment]
> > > @mrtuxa are the many issues with openbsd that @Jaskowicz1 is having an "us problem", or is there a fix? Do they need to be part of this change if we are claiming its fully supported?
> > 
> > i will do some tests the next days
> 
> Thank you :)

But the problem is i'm not very familiar with OpenBSD but I try my best

**Comment by Jaskowicz1** [comment]
> > > > @mrtuxa are the many issues with openbsd that @Jaskowicz1 is having an "us problem", or is there a fix? Do they need to be part of this change if we are claiming its fully supported?
> > > 
> > > 
> > > i will do some tests the next days
> > 
> > 
> > Thank you :)
> 
> But the problem is i'm not very familiar with OpenBSD but I try my best

Don't worry! If you manage to get it working, tell us what you did and I'll see if I can get it working too.

**Review by Jaskowicz1 — APPROVED** [review]
After #901 , I'm happy to say this PR is okay! DPP is functional and stable on OpenBSD, the issues that occur on OpenBSD are not related to DPP so people just need to use CMake (which we highly encourage for other platforms anyways).

**Pull request merged**
