### PR TITLE
fix: make execute_webhook supports avatar

### PR DESCRIPTION
**Pull request by yuto0214w**
1. It wasn't possible to edit webhook to change avatar, so edited it to use `wh.avatar`
2. This will override message.author.username if `wh.name` present

### CODE REVIEW

**Comment by yuto0214w** [comment]
Thanks for the feedback.
Fixed code style.
But for support of uploading avatar, as `avatar_url` only accepts http(s), it isn't possible to do like so other than modifying webhook.

**Comment by braindigitalis** [comment]
no pretty sure you can send a base64 encoded image in the image data, rather than a remote URL, same as when modifying webhook

**Comment by yuto0214w** [comment]
I tested dozen times, and read documentation but I couldn't seem to upload avatar without modifying webhook.
But as webhook avatar url format is `https://cdn.discordapp.com/avatars/:id/:hash.png`, I still don't think it's possible to do

**Comment by braindigitalis** [comment]
but those are user avatars, how do you get one uploaded to use it?

**Pull request merged**
