### PR TITLE
docs: fixed missing brackets in attachments.md

### PR DESCRIPTION
**Pull request by Jaskowicz1**
This PR is similar to #838, fixing a missing bracket in attachments.md.

- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.

### CODE REVIEW

**Review by Mishura4 — CHANGES_REQUESTED** [review]
Examples 1 and 3 still don't build :
```
[18:00:41] (miuna):~/dev/build/DPP/g++11> g++-11 attachments1.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
attachments1.cpp: In lambda function:
attachments1.cpp:13:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
   13 |             dpp::message msg(event.msg.channel_id, "Hey there, I've got a new file!");
      |                                    ^~~
```
```
[18:06:37] (miuna):~/dev/build/DPP/g++11> g++-11 attachments3.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
attachments3.cpp: In lambda function:
attachments3.cpp:14:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
   14 |             dpp::message msg(event.msg.channel_id, "");
      |                                    ^~~
```

**Review by braindigitalis — APPROVED** [review]

**Comment by braindigitalis** [comment]
> Examples 1 and 3 still don't build :
> 
> ```
> [18:00:41] (miuna):~/dev/build/DPP/g++11> g++-11 attachments1.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
> attachments1.cpp: In lambda function:
> attachments1.cpp:13:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
>    13 |             dpp::message msg(event.msg.channel_id, "Hey there, I've got a new file!");
>       |                                    ^~~
> ```
> 
> ```
> [18:06:37] (miuna):~/dev/build/DPP/g++11> g++-11 attachments3.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
> attachments3.cpp: In lambda function:
> attachments3.cpp:14:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
>    14 |             dpp::message msg(event.msg.channel_id, "");
>       |                                    ^~~
> ```

good spot, i didnt catch this!

**Comment by Jaskowicz1** [comment]
> Examples 1 and 3 still don't build :
> 
> ```
> 
> [18:00:41] (miuna):~/dev/build/DPP/g++11> g++-11 attachments1.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
> 
> attachments1.cpp: In lambda function:
> 
> attachments1.cpp:13:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
> 
>    13 |             dpp::message msg(event.msg.channel_id, "Hey there, I've got a new file!");
> 
>       |                                    ^~~
> 
> ```
> 
> ```
> 
> [18:06:37] (miuna):~/dev/build/DPP/g++11> g++-11 attachments3.cpp -Llibrary/ -ldpp -I../src/include/ -std=c++17
> 
> attachments3.cpp: In lambda function:
> 
> attachments3.cpp:14:36: error: ‘const struct dpp::slashcommand_t’ has no member named ‘msg’
> 
>    14 |             dpp::message msg(event.msg.channel_id, "");
> 
>       |                                    ^~~
> 
> ```

I'll sort that in the morning!

**Comment by Jaskowicz1** [comment]
Fixed up the issues that Mishura stated.

**Review by Commandserver — APPROVED** [review]

**Review by Mishura4 — APPROVED** [review]

**Pull request merged**
