### PR TITLE
misc(coro): deprecate sync methods when DPP_CORO is enabled

### PR DESCRIPTION
**Pull request by Mishura4**
- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.

### CODE REVIEW

**Comment by braindigitalis** [comment]
not sure I like this idea, as there are tons of bots using sync calls

**Comment by Mishura4** [comment]
We actively discourage using sync already, so the point is that they shouldn't, isn't it?

**Comment by braindigitalis** [comment]
that is true but we won't actually be removing them, the lib itself actively uses a couple of sync methods on startup to get number of shards etc.

**Comment by Mishura4** [comment]
I'll change it in the next few days

**Comment by Mishura4** [comment]
Wait i didn't mean to close it lmao

**Comment by Mishura4** [comment]
(The plan is still to change the warning very soon)

**Pull request closed without merging**
