### PR TITLE
fix memory leak on libstdc++

### PR DESCRIPTION
**Pull request by Mishura4**
fixes https://github.com/brainboxdotcc/DPP/issues/1091
truly a GNU moment

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Comment by Mishura4** [comment]
CHOTTO MATTE need to figure out why [6a47c6e](https://github.com/brainboxdotcc/DPP/pull/1112/commits/6a47c6e84ea26065a02821cc6fb53b72ae664741) is included

**Comment by Jaskowicz1** [comment]
37ed9925-8d98-4e65-89c2-fbbab8659bca_text

**Comment by Jaskowicz1** [comment]
Confirmed fixed on WSL
```
Memory currently at: 14127104
[2024-03-29 21:53:52] DEBUG: Shards started.
Memory currently at: 14127104
Memory currently at: 14127104
Memory currently at: 14127104
Memory currently at: 14127104
Memory currently at: 14127104
Memory currently at: 14127104
Memory currently at: 14127104
```

**Review by braindigitalis — APPROVED** [review]

**Comment by Jaskowicz1** [comment]
> Confirmed fixed on WSL
> 
> ```
> Memory currently at: 14127104
> [2024-03-29 21:53:52] DEBUG: Shards started.
> Memory currently at: 14127104
> Memory currently at: 14127104
> Memory currently at: 14127104
> Memory currently at: 14127104
> Memory currently at: 14127104
> Memory currently at: 14127104
> Memory currently at: 14127104
> ```

This seems to be a false positive from me. My image wasn't being sent so no memory was ever being added.

The issue still persists:
```
Memory currently at: 18853888
[2024-03-30 09:07:55] DEBUG: Shards started.
Memory currently at: 39813120
Memory currently at: 46161920
Memory currently at: 49405952
Memory currently at: 52580352
Memory currently at: 55758848
Memory currently at: 58998784
Memory currently at: 65417216
Memory currently at: 69402624
Memory currently at: 72646656
Memory currently at: 75821056
Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 78794752
Final Mem Check - Memory currently at: 38891520
```

**Pull request merged**
