### PR TITLE
add unit tests page

### PR DESCRIPTION
**Pull request by es183923**
This pull request adds a "Unit Tests" page to the Advanced Reference section.

### CODE REVIEW

**Comment by es183923** [comment]
I still need to write the docs for creating unit tests, but I don't know how you're supposed to do that 😅

**Comment by SirObby** [comment]
Aren't Unit tests run as checks when doing Pull Requests?

**Comment by es183923** [comment]
Yes, they are, but it’s a waste of time and resources if you use the CI to run unit tests. Running unit tests locally allow you to *quickly* check you have broken anything or not, while using the CI would take at least 10 minutes.

**Comment by Axyte** [comment]
> Aren't Unit tests run as checks when doing Pull Requests?

No. They are only run when it's already merged.

**Comment by braindigitalis** [comment]
I'm going to merge this as is and then write the additional technical section for creating unit tests.

**Pull request merged**
