### PR TITLE
Added dpp::cluster::guild_member_timeout_remove and its sync/coro versions

### PR DESCRIPTION
**Pull request by AA1999**
I've added dpp::cluster::guild_member_timeout_remove, dpp::cluster::guild_member_timeout_remove_sync and dpp::cluster::co_guild_member_timeout_remove and added documentation for them.

### CODE REVIEW

**Comment by braindigitalis** [comment]
how did you add the coro and sync version? did you do it by rerunning the builder scripts for it?

**Comment by AA1999** [comment]
I just called guild_timeout_remove_sync and co_guild_timeout with communication_disabled_until set to 0
Returned the result in the coro version

**Comment by braindigitalis** [comment]
the coro and sync are auto generated, you shouldn't manually put stuff in those files. when someone runs cmake it will remove your changes.

you need to make sure the auto generation picks up your changes. because they don't match the correct pattern this won't work as is. you should make them not just call another function and instead call the REST stuff

**Comment by AA1999** [comment]
Where's the script for these?
Is it in one of the CMakeLists?

**Comment by Jaskowicz1** [comment]
> Where's the script for these? Is it in one of the CMakeLists? Also why not call the function with a 0 parameter if I'm doing the exact same thing with one different variable?

No, it happens when you call `cmake -B build` or `cmake ..`

**Comment by AA1999** [comment]
I did use cmake -B and cmake --build before pushing
Dunno if that'd help or not

**Comment by braindigitalis** [comment]
it's a set of php scripts in the buildtools folder that do this, there's a base class, and a derived version of it for coro and sync.

you should not need to modify these scripts.

**Review by Jaskowicz1 — APPROVED** [review]
Better this time around!

**Pull request merged**
