### PR TITLE
feat: Change encryption to AEAD XChaCha20 Poly1305

### PR DESCRIPTION
**Pull request by Jaskowicz1**
This PR introduces `AEAD XChaCha20 Poly1305 (RTP Size)` as the encryption method for voice data.

`AEAD AES256-GCM (RTP Size)` will not be introduced in this PR as it is simply a suggestion (Discord declares it as a "preference", however, it's easier to just stick with `XChaCha20 Poly1305`) therefore, after discussions internally, we will stick with just `AEAD XChaCha20 Poly1305 (RTP Size)`

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Comment by Jaskowicz1** [comment]
Currently only have encrypting wrote (not sure if it works).

**Comment by braindigitalis** [comment]
we need to get this working then progress on to dave, lets split it into 2 parts

**Comment by Jaskowicz1** [comment]
Will do it over the weekend :)

**Comment by braindigitalis** [comment]
@Neko-Life has got this working with encryption and decryption using XChaCha20, this is tested so we should perhaps merge this, then put out a release to make the new encryption available in the interim before we can do the DAVE nonesense in a separate pr.

**Comment by Jaskowicz1** [comment]
Aye good idea

**Review by Mishura4 — APPROVED** [review]
YUGE. Rather clean code too!

**Pull request merged**
