### PR TITLE
Mention convertions for role user channel and emoji in dpp::utility, …

### PR DESCRIPTION
**Pull request by ruslan-ilesik**
…also added static converting functions to classes

### CODE REVIEW

**Comment by braindigitalis** [comment]
indentations and spacing on this is all a bit weird and needs fixing to match the coding style guide please.
is any existing methods removed or their signatures changed by this change?

**Comment by luktvpl** [comment]
I told him to read coding sytle but he said : https://discordapp.com/channels/825407338755653642/825407339254644779/1048148759915278357

**Comment by ruslan-ilesik** [comment]
> I told him to read coding sytle but he said : https://discordapp.com/channels/825407338755653642/825407339254644779/1048148759915278357

the difference in amount of spaces per TAB. Fixed it (it was showing same in Clion for me)

**Comment by ruslan-ilesik** [comment]
> indentations and spacing on this is all a bit weird and needs fixing to match the coding style guide please. is any existing methods removed or their signatures changed by this change?

I`ve fixed spacing. And fixed problem with removed signatures.

**Comment by Commandserver** [comment]
Wouldn't it be enough to have these helpers in the utility namespace?

**Comment by ruslan-ilesik** [comment]
> Wouldn't it be enough to have these helpers in the utility namespace?

Objects of such classes have this method inside of them, so I think it  would be not a bad idea to add static functions to this classes to do the same but without creating "complex" object.

**Pull request merged**
